[tool.poetry]
name = "small_problems"
version = "0.1.0"
description = ""
authors = ["Henry Madej <hmadej@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
